-- ############################################################################################################
-- ##  DANGER: WIPES THE WHOLE PUBLIC SCHEMA (every table, row, policy, function) of whichever project runs it. ##
-- ##  ONLY for a brand-new, empty Supabase project. NEVER run against the live Bide project.                   ##
-- ##  Prefer `supabase db reset` (local) or applying supabase/migrations/* in order.                          ##
-- ############################################################################################################
-- Bide: wipe schema "public", then replay ALL migrations in order:
--   1. 20261005150000_init.sql   2. 20261005160000_waitlist.sql   3. 20261006090000_agents.sql
-- Generated by concatenating supabase/migrations/*.sql verbatim — regenerate it when a migration is added.
-- Check the project name in the dashboard before pressing Run.
begin;
drop schema if exists public cascade;
create schema public;
grant usage on schema public to postgres, anon, authenticated, service_role;
grant all on schema public to postgres, service_role;
alter default privileges in schema public grant all on tables to postgres, service_role;
alter default privileges in schema public grant all on sequences to postgres, service_role;
alter default privileges in schema public grant all on functions to postgres, service_role;
alter default privileges in schema public grant select on tables to anon, authenticated;
commit;


-- ===== 20261005150000_init.sql =====
-- Bide schema (BUILD §7). Worker writes with the service key (bypasses RLS); anon/authenticated may only SELECT.
-- Amounts are stored as numeric (u64 on-chain can exceed bigint's signed range in theory; numeric is exact).

create table if not exists public.quotes (
  id bigint generated always as identity primary key,
  asset text not null,
  ts timestamptz not null default now(),
  fair_iv double precision,
  bid_iv double precision,
  venues jsonb not null default '[]'::jsonb,
  quick_pricing boolean not null default false,
  -- extra context for the UI / desk (what was priced)
  kind text,               -- put | call
  strike numeric,
  expiry timestamptz,
  spot double precision,
  fair_premium numeric,    -- USDC base units for `size`
  bid_premium numeric,
  premium_start numeric,
  premium_floor numeric
);
create index if not exists quotes_asset_ts on public.quotes (asset, ts desc);

create table if not exists public.desk_runs (
  id uuid primary key default gen_random_uuid(),
  plan_pubkey text,
  kind text not null check (kind in ('preview', 'round')),
  steps jsonb not null default '[]'::jsonb,
  proposal jsonb,
  verdict jsonb,
  final jsonb,
  memo jsonb,
  card jsonb,               -- plain-English card from the desk (worker/src/desk/card.ts)
  memo_hash text,
  tx_sig text,
  error_code text,
  status text not null default 'running',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists desk_runs_plan on public.desk_runs (plan_pubkey, created_at desc);
create index if not exists desk_runs_created on public.desk_runs (created_at desc);

create table if not exists public.plans (
  plan_pubkey text primary key,
  owner text not null,
  asset text not null,
  side text not null,
  phase text,
  quick boolean not null default false,
  target_strike numeric,
  exit_strike numeric,
  size_total numeric,
  size_filled numeric,
  horizon_end timestamptz,
  status text not null,
  updated_at timestamptz not null default now()
);
create index if not exists plans_owner on public.plans (owner);

create table if not exists public.rounds (
  round_pubkey text primary key,
  plan_pubkey text not null,
  kind text,
  strike numeric,
  size numeric,
  notional numeric,
  expiry timestamptz,
  auction_start timestamptz,
  premium_start numeric,
  premium_floor numeric,
  premium_paid numeric,
  fee_paid numeric,
  maker text,
  is_pool boolean not null default false,
  status text not null,
  settle_price numeric,
  exercised smallint,
  memo_hash text,
  sigs jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
create index if not exists rounds_plan on public.rounds (plan_pubkey);
create index if not exists rounds_status on public.rounds (status);

create table if not exists public.epochs (
  epoch_pubkey text primary key,
  asset text not null,
  kind text not null,
  expiry timestamptz not null,
  samples jsonb not null default '[]'::jsonb,
  sample_mask integer not null default 0,
  settle_price numeric,
  status text not null,
  updated_at timestamptz not null default now()
);
create index if not exists epochs_expiry on public.epochs (expiry desc);

create table if not exists public.telegram_links (
  wallet text not null,
  chat_id bigint not null,
  plan_pubkey text,
  created_at timestamptz not null default now(),
  primary key (wallet, chat_id)
);

-- Cached reference data (Jupiter Lend APY / price — mainnet reference only, never settlement).
create table if not exists public.reference_data (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

-- RLS: anon/authenticated can SELECT public tables; nobody but the service role writes.
alter table public.quotes enable row level security;
alter table public.desk_runs enable row level security;
alter table public.plans enable row level security;
alter table public.rounds enable row level security;
alter table public.epochs enable row level security;
alter table public.reference_data enable row level security;
alter table public.telegram_links enable row level security; -- no anon policy: wallet↔chat_id stays private

create policy "anon read quotes" on public.quotes for select to anon, authenticated using (true);
create policy "anon read desk_runs" on public.desk_runs for select to anon, authenticated using (true);
create policy "anon read plans" on public.plans for select to anon, authenticated using (true);
create policy "anon read rounds" on public.rounds for select to anon, authenticated using (true);
create policy "anon read epochs" on public.epochs for select to anon, authenticated using (true);
create policy "anon read reference_data" on public.reference_data for select to anon, authenticated using (true);

-- Realtime for the app (/desk feed, /plan timeline, /auctions tape).
do $$ begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    alter publication supabase_realtime add table public.desk_runs, public.rounds, public.plans, public.epochs;
  end if;
end $$;

-- ===== 20261005160000_waitlist.sql =====
-- Landing-page waitlist (app/app/api/waitlist/route.ts inserts with the anon key).
-- RLS: anon may INSERT only. No SELECT/UPDATE/DELETE policies, so emails are never readable with the anon key.

create table if not exists public.waitlist (
  id uuid primary key default gen_random_uuid(),
  email text not null unique check (char_length(email) <= 200),
  target_note text check (target_note is null or char_length(target_note) <= 80), -- "at what price would you buy SOL?"
  wallet text check (wallet is null or char_length(wallet) between 32 and 44),
  source text not null default 'landing' check (char_length(source) <= 40),
  created_at timestamptz not null default now()
);

alter table public.waitlist enable row level security;

drop policy if exists "anon insert waitlist" on public.waitlist;
create policy "anon insert waitlist" on public.waitlist
  for insert to anon, authenticated
  with check (true);

-- Table privileges: insert only for API roles (RLS above still applies).
revoke all on public.waitlist from anon, authenticated;
grant insert on public.waitlist to anon, authenticated;

-- ===== 20261006090000_agents.sql =====
-- Bide AI agents v2 (docs/ai-agents.md, as revised 2026-10-06): maker agent stances + per-round bid ledger with P&L,
-- intake runs, and the rounds columns that the desk's deterministic `recent_outcomes` tool needs.
-- Worker writes with the service key (bypasses RLS). anon/authenticated may only SELECT the public tables.
-- No LLM "lessons" table: reflection memory was cut in favour of deterministic outcome statistics.

-- rounds: asset + auction timing (seconds-to-fill is derived from start/floor/paid/auction_secs).
alter table public.rounds add column if not exists asset text;
alter table public.rounds add column if not exists auction_secs integer;
alter table public.rounds add column if not exists pool_delay_secs integer;
create index if not exists rounds_asset_start on public.rounds (asset, auction_start desc);
create index if not exists rounds_plan_start on public.rounds (plan_pubkey, auction_start desc);

-- One stance per maker per (asset, epoch, round kind). Decided before the auction window; rounds derive bids from it.
create table if not exists public.maker_stances (
  id uuid primary key default gen_random_uuid(),
  stance_key text not null,              -- '<asset_pubkey>:<epoch_pubkey>:<put|call>'
  asset text not null,
  epoch_pubkey text not null,
  expiry timestamptz not null,
  kind text not null check (kind in ('put', 'call')),
  maker text not null,                   -- 'maker-1' | 'maker-2'
  persona text not null,
  source text not null check (source in ('llm', 'fallback')),
  model text,
  stance text check (stance in ('bid', 'pass')),
  spread_pct double precision,
  thesis text,
  confidence double precision,
  grounded boolean,
  fallback_reason text,
  context jsonb,                         -- the public market inputs the maker saw (no desk memo, no plan bounds)
  stance_hash text not null,             -- sha256 of canonical JSON of the stance record
  latency_ms integer,
  created_at timestamptz not null default now()
);
create index if not exists maker_stances_key on public.maker_stances (stance_key, maker, created_at desc);
create index if not exists maker_stances_created on public.maker_stances (created_at desc);

-- Per-maker, per-round bid ledger. pnl_usdc = settlement value − premium paid (USDC base units), set at resolve.
create table if not exists public.maker_bids (
  id uuid primary key default gen_random_uuid(),
  round_pubkey text not null,
  plan_pubkey text not null,
  maker text not null,
  maker_pubkey text not null,
  stance_id uuid references public.maker_stances (id),
  source text not null check (source in ('llm', 'fallback')),
  stance text not null check (stance in ('bid', 'pass')),
  spread_pct double precision,
  fair_at_bid numeric,                   -- consensus CEX fair premium for this round (USDC base units, total)
  bid numeric,                           -- null when the maker passed
  thesis text,
  confidence double precision,
  reason text,                           -- fallback reason / clamp note
  bid_hash text not null,
  took boolean not null default false,
  tx_sig text,
  pnl_usdc numeric,                      -- signed; losses included
  created_at timestamptz not null default now()
);
create index if not exists maker_bids_round on public.maker_bids (round_pubkey);
create index if not exists maker_bids_plan on public.maker_bids (plan_pubkey, created_at desc);
create index if not exists maker_bids_maker on public.maker_bids (maker, created_at desc);

-- Intake: free text → draft form fields. User text: no anon access.
create table if not exists public.intake_runs (
  id uuid primary key default gen_random_uuid(),
  text text not null,
  status text not null default 'running' check (status in ('running', 'done', 'error')),
  fields jsonb,
  assumptions jsonb,
  questions jsonb,
  model text,
  error text,
  latency_ms integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.maker_stances enable row level security;
alter table public.maker_bids enable row level security;
alter table public.intake_runs enable row level security; -- no anon policy: user free text stays private

drop policy if exists "anon read maker_stances" on public.maker_stances;
create policy "anon read maker_stances" on public.maker_stances for select to anon, authenticated using (true);
drop policy if exists "anon read maker_bids" on public.maker_bids;
create policy "anon read maker_bids" on public.maker_bids for select to anon, authenticated using (true);

do $$ begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and tablename = 'maker_bids') then
    alter publication supabase_realtime add table public.maker_bids;
  end if;
end $$;
