[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
bide = "4bwTwLAZqPMLSbdvQQ9UrePJiRBUKgiA8TKV3ydo4tqe"

[programs.devnet]
bide = "4bwTwLAZqPMLSbdvQQ9UrePJiRBUKgiA8TKV3ydo4tqe"

[provider]
cluster = "devnet"
wallet = "keys/deployer.json"

[scripts]
test = "pnpm --filter @bide/tests test"
