// Copy the anchor build outputs into packages/shared/src/idl (run after every `anchor build`).
import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "packages/shared/src/idl");
mkdirSync(out, { recursive: true });
copyFileSync(join(root, "target/idl/bide.json"), join(out, "bide.json"));
copyFileSync(join(root, "target/types/bide.ts"), join(out, "bide.ts"));
const json = readFileSync(join(root, "target/idl/bide.json"), "utf8");
writeFileSync(
  join(out, "idl.ts"),
  `// GENERATED by scripts/sync-idl.mjs — do not edit\nimport type { Bide } from "./bide.js";\nexport const IDL: Bide = ${json.trim()} as unknown as Bide;\nexport type { Bide };\n`,
);
console.log("IDL synced:", JSON.parse(json).instructions.length, "instructions");
